config/routes.rb
Bookster::Application.routes.draw do
  
  scope "(:locale)", :locale => /en|de|de-ZW/ do
    get "pages/home"

    get "pages/wthit"

    get "pages/who"

    devise_for :users
 
    resources :users

    resources :books do
      resources :chapters
    end

    root :to => "pages#home"
  end

  

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :title, :subtitle
  has_many :chapters, :order => 'created_at ASC'
  belongs_to :user
  
  validates :title, :presence => :true
  
  def to_param
    "#{id}-#{title.downcase}-by-#{user.to_s}".gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :new]
  
  
  
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    do_response @books
    #
    #respond_to do |format|
     # format.html # index.html.erb
      #format.json { render :json => @books }
      #end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @chapters = @book.chapters
    wl = WhatLanguage.new(:all)
    @lang = ""
    @book.chapters.each do
      @lang = wl.language(@book.chapters[0].content).to_s.capitalize
    end

    do_response @book.to_json(:include => :chapters)
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    do_response @book
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])
    @book.user = current_user
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, :notice => 'Book was successfully created.' }
        format.json { render :json => @book, :status => :created, :location => @book }
      else
        render_error_response("", "new", @book)
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.user == current_user
        if @book.update_attributes(params[:book])
          successful_update_response @book
        else
          failed_update_response @book
        end
      else
        no_right_response @chapter
      end
    end
  end
  
  def successful_update_response(model)
    format.html { redirect_to model, :notice => 'Book was successfully edited.' }
    format.json { head :no_content }
  end
  
  def failed_update_response(model)
    format.html { render :action => "edit" }
    format.json { render :json => model.errors, :status => :unprocessable_entity }
  end
  
  def no_right_update_response(model)
    format.html { render :action => "edit" , :alert => "U HAVE NO RIGHTS!" }
    format.json { render :json => model, :status => :unprocessable_entity }
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    if @book.user == current_user
      @book.destroy
    end

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group<%= " error" unless ! @book.errors[:title].any? %>">
    <%= f.label :title, t('book.title'), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group<%= " error" unless ! @book.errors[:subtitle].any? %>">
    <%= f.label :title, t('book.subtitle'), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subtitle, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit t('book.create'), :class => 'btn btn-primary' %>
    <%= link_to t('cancel'),
                books_path, :class => 'btn' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%- model_class = @book.class -%>
<h1><%=t 'book.edit' %></h1>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
	<%- model_class = Book.new.class -%>
<div class="page-header">
	<h1><%=t 'book.name_pl' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t 'book.title' %></th>
      <th><%= t 'book.author' %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= link_to book.user,  book.user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<%- model_class = @book.class -%>
<h1><%= t 'book.new' %></h1>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = @book.class -%>

<div class="page-header">
	<div class="pull-right">
		<% if current_user == @book.user %>
			<%= link_to new_book_chapter_path(@book), :class=>"btn btn-primary" do %>
				<i class='icon-plus-sign'></i>
				<%= t 'chapter.create' %>
			<% end %>
			
			<%= link_to book_path(@book), :method => 'delete', :confirm => "Do you really want to delete this book?", :class => 'btn btn-danger' do %>
				<i class="icon-trash"></i>
				<%= t 'book.remove' %>
			<% end %>
		<%end%>
	</div>
	<h1>
		<%= best_in_place_if current_user == @book.user, @book, :title %>
		<small>
			<em>
				 <%= t 'book.written_by' %> <strong><%= link_to @book.user, @book.user %></strong>
			</em>
		</small>
	</h1>
	<%= best_in_place_if current_user == @book.user, @book, :subtitle %>
</div>

<% if @book.chapters.any? %>
	<h3><%= t 'chapter.name_pl'%>:</h3>
    <ol>
        <% @book.chapters.each do |chapter| %>
	        <li>
				<%= link_to chapter.title, [@book, chapter] %>
			</li>
	    <% end %>
	</ol>
<% end %>
<% if !@lang.empty? %>
<div class="pull-right">
	<small><%= t 'language' %>: <strong><%= @lang %></strong></small>
</div> 
<% end %>