config/routes.rb
Bookster::Application.routes.draw do
  
  scope "(:locale)", :locale => /en|de|de-ZW/ do
    get "pages/home"

    get "pages/wthit"

    get "pages/who"

    devise_for :users
 
    resources :users

    resources :books do
      resources :chapters
    end

    root :to => "pages#home"
  end

  

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :title, :content

  belongs_to :book
    
  validates :content, :length => {:minimum => 10}, :presence => :true
  validates :title, :presence => :true
  
  def to_param
    "#{id}-#{title.downcase}".gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')
  end

  def next
  	print id
    book.chapters.where("id > ?", id).first
  end

  def prev
    book.chapters.where("id < ?", id).first
  end


end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_filter :find_book
  before_filter :authenticate_user!, :except => [:index, :show]
  
  require 'whatlanguage'
  
  
  # GET /chapters/1
  # GET /chapters/1.json
  def show
    @chapter = Chapter.find(params[:id])
    @book = @chapter.book

    do_response @chapter
  end

  # GET /chapters/new
  # GET /chapters/new.json
  def new
    @chapter = @book.chapters.new

    do_response @chapter
  end

  # GET /chapters/1/edit
  def edit
    @chapter = Chapter.find(params[:id])
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = @book.chapters.build(params[:chapter])
    
     respond_to do |format|
       if @book.user == current_user
          if @chapter.save
            format.html { redirect_to [@book, @chapter], :notice => 'Chapter was successfully added.' }
            format.json { render :json => [@book, @chapter], :status => :created, :location => [@book, @chapter] }
          else
            render_error_response("", "new", @chapter)
          end
       else
         render_error_response("U HAVE NO RIGHTS", "new", @chapter)
       end
     end
  end

  # PUT /chapters/1
  # PUT /chapters/1.json
  def update
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      if @book.user == current_user
        if @chapter.update_attributes(params[:chapter])
          format.html { redirect_to [@book, @chapter], :notice => 'Chapter was successfully edited.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @chapter.errors, :status => :unprocessable_entity }
        end
      else
        format.html { render :action => "edit" , :alert => "U HAVE NO RIGHTS!" }
        format.json { render :json => @chapter, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter = Chapter.find(params[:id])
    if @chapter.book.user == current_user
      @chapter.destroy
    end
    
    respond_to do |format|
      format.html { redirect_to @book }
      format.json { head :no_content }
    end
  end
  
  private
    def find_book
      @book = Book.find(params[:book_id].to_i)
    end

end

app/helpers/chapters_helper.rb
module ChaptersHelper

end

app/views/chapters/_form.html.erb
<%= form_for [@book,@chapter], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group<%= " error" unless ! @chapter.errors[:title].any? %>">
    <%= f.label :title, t('chapter.title'), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group<%= " error" unless ! @chapter.errors[:content].any? %>">
    <%= f.label :content, t('chapter.content'), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :rows => 10, :cols => 140 %>
      <p class="help-block"><%= t 'markdown_advice'%></p>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit t('chapter.create'), :class => 'btn btn-primary' %>
    <%= link_to t('cancel'),
                book_path(@chapter.book), :class => 'btn' %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<div class="page-header">
	<h1><%= t('chapter.edit', :title => @chapter.title) %></h1>
</div>
<%= render :partial => 'form' %>

app/views/chapters/new.html.erb
<%- model_class = @chapter.class -%>
<h1><%= t 'chapter.create' %></h1>
<%= render :partial => 'form' %>

app/views/chapters/show.html.erb
<%- model_class = @chapter.class -%>
<div class="page-header">
	
	<% if current_user == @book.user %>
		<div class="pull-right">
			<%= link_to edit_book_chapter_path(@book), :class => 'btn' do %>
				<i class="icon-edit"></i>
				<%= t 'chapter.edit', :title => "Chapter" %>
			<% end %>
			<%= link_to book_chapter_path([@book]), :method => 'delete', :confirm => "Do you really want to delete this chapter?", :class => 'btn btn-danger' do %>
				<i class="icon-trash"></i>
				<%= t 'chapter.delete' %>
			<% end %>	 
		</div>
	<% end %>
	<h1>
		<%= @chapter.title %> 
		<small>
			<%= t 'chapter.from'%> <%= link_to @chapter.book.title, @chapter.book %>
			<em>
				 <%= t 'book.written_by'%> <strong><%= link_to @chapter.book.user, @chapter.book.user %></strong>
			</em>
		</small>
		
	</h1>
</div>
<div class="row">
	<div class="span9">
  		<div>
  			<%= markdown h @chapter.content %>
  		</div>
  		
	</div>
	<div class="span3">
		<h3><%= t 'chapter.name_pl' %>:</h3>
    	<ol>
        	<% @chapter.book.chapters.each do |chapter| %>
	        	<li>
					<% if @chapter == chapter %>
					<%= chapter.title %>
					<% else %>
					<%= link_to chapter.title, [@book, chapter] %>
					<% end %>
				</li>
	    	<% end %>
		</ol>

	</div>
	<div class="span12">
		<div>
  			<span>
  				<%= link_to t('chapter.prev')+": "+ @chapter.prev.title, [@book, @chapter.prev], :class => 'btn' unless @chapter.prev == nil %>
  			</span>
  			<span class="pull-right">
  				<%= link_to t('chapter.next')+": "+ @chapter.next.title, [@book, @chapter.next], :class => 'btn' unless @chapter.next == nil %>
  			</span>
  		</div>
  	</div>

</div>