config/routes.rb
Bookster::Application.routes.draw do
  
  scope "(:locale)", :locale => /en|de|de-ZW/ do
    get "pages/home"

    get "pages/wthit"

    get "pages/who"

    devise_for :users
 
    resources :users

    resources :books do
      resources :chapters
    end

    root :to => "pages#home"
  end

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    
  <title>booksta</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="navbar navbar-fixed-top">
    	<div class="navbar-inner">
      		<div class="container">
        		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          			<span class="icon-bar"></span>
          			<span class="icon-bar"></span>
          			<span class="icon-bar"></span>
        		</a>
				<strong>
        			<%= link_to "booksta", root_url, :class => "brand"%>
				</strong>
        		<div class="nav-collapse">
          			<ul class="nav">
	        			<li <%= active?("/") %>><%= link_to t('page.home') , root_url %></li>
            			<li <%= active?(books_path) %>><%= link_to t('book.all'), books_path %></li>
            			<li <%= active?(new_book_path) %>><%= link_to t('book.new'), new_book_path unless !user_signed_in? %></li>
					</ul>
					<ul class="nav pull-right">
						<li class="dropdown" %>
							<a href="#"
						       class="dropdown-toggle"
						       data-toggle="dropdown" id="account_thing">
								<i class="icon-user" id="account_thing_icon"></i>
						          <% if user_signed_in? %>
								  	<%= current_user.username %>
								  <%else %>
								  <%= t 'user.account' %>
								  <%end%>
						          <b class="caret"></b>
						    </a>
						    <ul class="dropdown-menu pull-right">
								<% if !user_signed_in? %>
									<li><%= link_to t('user.sign_in'), new_user_session_path %></li>
									<li class="divider"></li>
									<li><%= link_to t('user.sign_up'), new_user_registration_path %></li>
								<% else %>
									<li><%= link_to t('user.profile'), current_user %></li>
									<li class="divider"></li>
									<li><%= link_to t('book.new'), new_book_path %>
									</li>
									<li><%= link_to t('user.sign_out'), destroy_user_session_path, :method => :delete%></li>
								<% end %>
						    </ul>
						</li>
          			</ul>
        		</div>
      		</div>
    	</div>
	</div>
	<div class="container">
		<% if notice %>
    		<p class="alert alert-success"><%= notice %><a class="close" href="#" data-dismiss="alert">&times;</a></p>
    	<%end%>
    	<% if alert %>
    		<p class="alert alert-error"><%= alert %><a class="close" href="#" data-dismiss="alert">&times;</a></p>
	    <%end%>

		<div class="content">
			<%= yield %>
		</div>
		<hr />
		<footer>
			<br />

			<p class="pull-left">
				<%= link_to t('page.what.title'), pages_wthit_path %>&nbsp;|&nbsp;<%= link_to t('page.who.title'), pages_who_path %>
			</p>
			<p class="pull-right">
			<%= link_to_unless I18n.locale == :en, "English", locale: :en %>
			|
			<%= link_to_unless I18n.locale == :de, "Deutsch", locale: :de %>
			|
			<%= link_to_unless I18n.locale.to_s == "de-ZW", "HeinzPeda Deutsch", locale: "de-ZW" %>
			</p> 
			<p>
				Made by bigteddy, 2012-2013
			</p>
			<br/>
		</footer>
		<%= debug(params) if Rails.env.development? %>
	</div>
	
    <%= javascript_include_tag "application" %>
	
</body>
</html>